package com.dani.springboot.backend.miBillar.models.entity;

// default package
// Generated 23 mar 2023 18:44:41 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;

/**
 * Partidas generated by hbm2java
 */
@Entity
@Table(name = "partidas")
public class Partidas implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private Jugadores jugadores;
	private Date fecha;
	private String rival;
	private Integer carambolas;
	private Integer entradas;
	private Integer serieMax;
	private String resultado;
	private Integer numeroMesa;

	public Partidas() {
	}

	public Partidas(int id) {
		this.id = id;
	}

	public Partidas(int id, Jugadores jugadores, Date fecha, String rival, Integer carambolas, Integer entradas,
			Integer serieMax, String resultado, Integer numeroMesa) {
		this.id = id;
		this.jugadores = jugadores;
		this.fecha = fecha;
		this.rival = rival;
		this.carambolas = carambolas;
		this.entradas = entradas;
		this.serieMax = serieMax;
		this.resultado = resultado;
		this.numeroMesa = numeroMesa;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jugador_id")
	public Jugadores getJugadores() {
		return this.jugadores;
	}

	public void setJugadores(Jugadores jugadores) {
		this.jugadores = jugadores;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", length = 13)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@Column(name = "rival")
	public String getRival() {
		return this.rival;
	}

	public void setRival(String rival) {
		this.rival = rival;
	}

	@Column(name = "carambolas")
	public Integer getCarambolas() {
		return this.carambolas;
	}

	public void setCarambolas(Integer carambolas) {
		this.carambolas = carambolas;
	}

	@Column(name = "entradas")
	public Integer getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Integer entradas) {
		this.entradas = entradas;
	}

	@Column(name = "serie_max")
	public Integer getSerieMax() {
		return this.serieMax;
	}

	public void setSerieMax(Integer serieMax) {
		this.serieMax = serieMax;
	}

	@Column(name = "resultado", length = 10)
	public String getResultado() {
		return this.resultado;
	}

	public void setResultado(String resultado) {
		this.resultado = resultado;
	}

	@Column(name = "numero_mesa")
	public Integer getNumeroMesa() {
		return this.numeroMesa;
	}

	public void setNumeroMesa(Integer numeroMesa) {
		this.numeroMesa = numeroMesa;
	}

}
